[package]
name = "untron-p2"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
hex-literal = "0.4.1"
log = "0.4.22"
plonky2x = { git = "https://github.com/succinctlabs/succinctx.git" }
rand = "0.8.5"
sha2 = "0.10.8"
